### ISSUE TITLE
Kodi Services Port Not Forwarded

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [ehough/docker-kodi#8]
Hi,

I am new to Docker (although proficient in a Linux environment), so please excuse me if this is a daft question.

I set this container up on my Ubuntu Desktop (18.04 running Wayland) which is running the latest version of Docker.

I have added this container to my Docker stack using the below Docker Compose settings:

```
  kodi:
   image: erichough/kodi:latest
   container_name: kodi
   restart: always
   ports:
    - target: 5634
      published: 5634
      protocol: tcp
      mode: host
```
the command that I am using to run Kodi is as follows:

`x11docker --home --hostdisplay --pulseaudio --gpu --silent -- "-v /media/daniel:/media:ro" erichough/kodi`

When I set Kodi to listen on port 5634 for remote control (and have "Allow control from other systems" checked), I cannot seem to be able to get a route through to the Kodi instance.

I am sure this may be trivial, but this is the last hurdle in getting my Kodi instance fully Dockerized.

Thanks in advance!
